curl -H "Authorization: Bearer <ACCESS_TOKEN>" http://localhost:8000/protected

###

curl -X POST 'http://localhost:8080/realms/demo/protocol/openid-connect/token' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'username=admin' \
-d 'password=admin' \
-d 'grant_type=password' \
-d 'client_id=admin-cli'


###

curl -X POST http://localhost:8080/realms/demo/protocol/openid-connect/token \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=password" \
  -d "client_id=flask-app" \
  -d "client_secret=xxxxxl" \
  -d "username=user1" \
  -d "password=pass"


###

  curl -X POST http://localhost:8080/realms/demo/protocol/openid-connect/token \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=client_credentials" \
  -d "client_id=user1-mytest-key-6" \
  -d "client_secret=xxxxx"


###

  
  curl -X POST "http://localhost:8080/realms/demo/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=password" \
  -d "client_id=admin-cli" \
  -d "username=admin" \
  -d "password=admin"


###

  curl http://localhost:8000/protected \
  -H "Authorization: Bearer xxxx"


###
curl -X POST "http://localhost:8080/realms/demo/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "client_id=api-backend" \
  -d "client_secret=xxxx" \
  -d "grant_type=client_credentials"

###

